setValues = set()

n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)
n = input("Enter the value: ")
setValues.add(n)

setValues.add(3)
print("Your final unique set : ", setValues)
